name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'K8s/**'
      - 'helm-go-chart/**'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          #go-version: '1.22'
          go-version-file: 'go.mod'

      - name: Build Go App
        run: go build -o go-web-app

      - name: Run Tests
        run: go test ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Clear Go Module Cache (Crucial Fix)
        run: |
          go clean -modcache
          echo "✅ Go module cache cleared"

      - name: Clear GolangCI-Lint Cache
        run: |
          rm -rf ~/.cache/golangci-lint || true
          echo "✅ GolangCI-Lint Cache cleared"

      - name: Run Golang Linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61.0
          args: --timeout=5m

  docker-build-push:
    runs-on: ubuntu-latest
    needs: [build-test, lint]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/go-web-app:${{ github.run_id }}

  update-helm:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: Update Image Tag in Helm Chart
        run: |
          sed -i 's/tag: .*/tag: "${{ github.run_id }}"/' helm-go-chart/values.yaml

      - name: Commit and Push Helm Update
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "Karthikeya"
          git add helm-go-chart/values.yaml
          git commit -m "Update image tag to ${{ github.run_id }}"
          git push

